### ISSUE TITLE
Mission and Tea of the Month section

### ISSUE THREAD

**Issue by farishkash** [lollablows/1-19-18-Tea-Cozy#1]
![tea_cozy](https://user-images.githubusercontent.com/5844161/35367977-f58cf800-0135-11e8-9a53-045798d4a8a6.png)

Mission section the text is one line.  It needs a few fixes.  The mission banner div should be less in height and have a black background for both text inside of it.

Tea of the month is on the same side.  This is happening you are using inline-block.  Since my screen is wide enough this div is moving inline with the mission section.  Inline block will always do this.

**Comment by giliuslukas** [comment]
Thank you!
