### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [lollablows/1-19-18-Tea-Cozy#5]
Overall met expectations.

This is a harder review for me.  Structural your html and css is great.  I didn't see any issues or red flags.  I really feel that you shouldn't be struggling especially based on me taking a look at your dasmoto review and your mytimes project.

If you feel that I am wrong let me but it seems like you are struggling with two concepts.

What does inline do and how to manage flexbox.

Inline-block and inline-flex is in relation to the other parent elements around it and has nothing to do with the children inside.

When it comes to flexbox itself I want to leave you two resources.

flexboxfroggy.com and this youtube video which I feel is one of the best one out there.
https://youtu.be/Mkza0N8NiK4

To prepare you for the final projects, look at media queries. See if you can make this site fit inside of a mobile device by using one. You will be doing this heavily in your final projects.

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

https://www.w3schools.com/css/css3_mediaqueries_ex.asp

**Comment by giliuslukas** [comment]
That video helped thank you! I was struggling with the concept, just had to put more time in. Thanks for the review!
